version: '2'
services:
  rolodex:
    image: smartproxy:1.0    ports:
      - "10389:10389"  
      - "9999:9999"
    expose:
      - 10389
      - 9999
    volumes:
      - /var/rolodex-data:/rolodex-data
      - /certs:/certs
    environment:
      DEBUG: 'true'
      CONNECTORS: '10.30.22.5:636:CN=svc-deadbolt\,OU=Service%20Accounts\,OU=xstream\,DC=namerica\,DC=ef86\,DC=net:tg4Zjr3Ygqh9WVYrIX9:true:adcert.jks:rolodex:AD:true:'
      DEFAULTADTENANTDN: 'OU=Rolodex,OU=Customers,OU=xstream,DC=namerica,DC=ef86,DC=net'
      ISADREADONLY: 'false'
      DEFAULTADCONSTR: '10.30.22.5:636:CN=svc-deadbolt,OU=Service%20Accounts,OU=xstream,DC=namerica,DC=ef86,DC=net:tg4Zjr3Ygqh9WVYrIX9' 
      USETLS: 'true'
      CERTNAME: 'server.ks'
      CERTPWD: 'secret'
      
 
