version: '2'
services:
  smartproxy:
    image: smartproxy:latest
    ports:
      - "10389:10389"
      - "5005:5005"  
    expose:
      - 10389
      - 5005
   # volumes:
   #   - /var/rolodex-data:/rolodex-data
    environment:
      DEBUG: 'true'
      CONNECTORS: '172.29.192.1:12389:uid=admin\,ou=system:secret:ou=system:ou=users\,ou=system:apacheds,192.168.99.100:389:cn=admin\,dc=example\,dc=org:admin:ou=onscaleds\,dc=example\,dc=org:ou=users\,ou=onscaleds\,dc=example\,dc=org:openldap'
  
      
 