version: '2'
services:
  rolodex:
    image: smartproxy:1.0
    ports:
      - "10389:10389"  
      - "9999:9999"  
    expose:
      - 10389
      - 9999
    #volumes:
     #- /var/data:/data
    environment:
      DEBUG: 'true'
      # connectors definition: hostname:port:bind-name:pwd:isTLS:keystore:ks-secret
      CONNECTORS: ''
      DEFAULTADTENANTDN: 'OU=Rolodex,OU=Customers,OU=xstream,DC=namerica,DC=ef86,DC=net'
      ISADREADONLY: 'false'
      DEFAULTADCONSTR: '' 
      CONNECTORHOST: 'localhost'
      DEFAULT_HOST: ldap
      DEFAULT_PORT: 389
      DEFAULT_USERNAME: 'cn=admin,dc=deadbolt,dc=emc'
      DEFAULT_PASSWORD: 'Password1'
      DEFAULT_SOURCETENANTDN: 'ou=tenants,dc=deadbolt,dc=emc'
      DEFAULT_LDAPTYPE: 'openLdap'
      PARTITIONLOC: 'file:///data'
      TRANSPARENTPROXY: 'true'
      USETLS: 'false'
     
    depends_on:
      - ldap
    links:
      - ldap
      
  ldap:
    image: docker-registry.core.rcsops.com/coreservices-snapshots/deadbolt/openldap
    environment: 
      LDAP_DOMAIN: deadbolt.emc
      LDAP_ADMIN_PASSWORD: Password1
    ports:
      - "389:389"
    expose:
      - 389
    #volumes:
      #- c:/docker/openldap/ldap:/var/lib/ldap
     # - c:/docker/openldap/slap.d:/etc/ldap/slapd.d
 
