apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rolodex.fullname" . }}
  labels:
    app: {{ template "rolodex.name" . }}
    chart: {{ template "rolodex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.ldap.install }}{{ else }}ldap-password: {{ .Values.ldap.password | b64enc | quote }}{{ end }}
  connectors: {{ .Values.connectors | b64enc | quote }}
  defaultADconnStr: {{ .Values.defaultADconnStr | b64enc | quote }}
