apiVersion: v1
kind: Service
metadata:
  name: {{ template "rolodex.fullname" . }}
  labels:
    app: {{ template "rolodex.name" . }}
    chart: {{ template "rolodex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}{{ if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}{{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
    - port: {{ .Values.connector.port }}
      targetPort: ldap
      protocol: TCP
      name: ldap
  selector:
    app: {{ template "rolodex.name" . }}
    release: {{ .Release.Name }}
