# Default values for rolodex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker-registry.com/coreservices/smartproxy
  tag: 3.0.70
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9179
  adminPort: 9180

ldap:
  install: true
  type: openldap
  # if install = false then use defined host/password
  host: openldap 
  port: 389
  username: cn=admin,dc=deadbolt,dc=emc
  # if install = false then use defined host/password
  password: password
  sourceTenantDN: ou=tenants,dc=deadbolt,dc=emc

connector:
  host: localhost
  port: 10389
  
connectors: 

defaultADTenantDn: OU=Rolodex,OU=Customers,OU=xstream,DC=namerica,DC=ef86,DC=net

isAdReadyOnly: false

defaultADconnStr: 

persistence:
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 1Gi
  subPath: "rolodex-data"

  # annotations: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
